### ISSUE TITLE
Get high res images for owned listings

### ISSUE THREAD

**Issue by Andrew-Lev** [simonsruggi/Airbnb-Free-High-Quality-Photo-Downloader#1]
The code successfully gets all the listing images, but they are of reduced resolution.  
If you own the listing its ideal to grab high res images. 

Bnb suggests to do this by removing the /im/ from the urls.
```
    def download_image(self, url):
        url = url.replace('/im/pictures', '/pictures')
```

**Comment by simonsruggi** [comment]
Fixed, thanks!
